events {}

http {
  server {
    listen 80;
    server_name coludfarm.fun www.cloudfarm.fun;

    #frontend
    location / {
      proxy_pass http://frontend_container:5173;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    #backend
    location /api/ {
      proxy_pass http://backend_container:5000/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }


  }
}
